### ISSUE TITLE
IPN Fails validate in grails 2.2.4 with secial chars ö ä é ..etc

### ISSUE THREAD

**Issue by littleiffel** [paypal/merchant-sdk-java#18]
HI,

i tried using using merchantsdk with grails. IPN Verification works fine using the sample code you provided, but as soon as one field contains special characters the IPN validation fails. I change my Encoding in PayPal settings to UTF-8, but still fails.

The IPN Simulator fails too as soon as there are special chars in one field like name, address...etc. And the PayPal sandbox is broken so cannot set Charset here.

However this code works

```
       def server = 'https://www.paypal.com/cgi-bin/webscr'
        
        params.cmd = "_notify-validate"
        def queryString = params.toQueryString()[1..-1]

        log.debug "Sending back query $queryString to PayPal server "
        def url = new URL(server)
        def conn = url.openConnection()
        conn.doOutput = true
        def writer = new OutputStreamWriter(conn.getOutputStream())
        writer.write queryString
        writer.flush()

        def result = conn.inputStream.text?.trim()

        log.debug "Got response from PayPal IPN $result"
        def isIpnVerified = (result == 'VERIFIED')
```

**Comment by jostster** [comment]
Any update on this? Having the same issue.

**Comment by sgo** [comment]
I ended up not using the PayPal SDK to validate the IPN message as there are multiple systems all trying to do this work and no way to resolve them all.
I think I just looked at the sources in the PayPal SDK and removed the part that was messing things up.

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
