### ISSUE TITLE
Express Checkout with Setting Up a Billing Agreement 

### ISSUE THREAD

**Issue by sempervirescent** [paypal/merchant-sdk-java#20]
Hi,

I am looking into implementing the Express Checkout as tested with the PayPal API Explorer:
https://devtools-paypal.com/apiexplorer/PayPalAPIs

I need to generate a BAID (Billing Agreement ID) using the PayPal API. I am doing a Set ExpressCheckout in the API Explorer, and when the user confirms the payment I am executing a CreateBillingAgreement instead of DoExpressCheckoutPayment. I am looking into implementing the same functionality with the Merchant SDK.  

During my testing, the GetExpressCheckoutDetails response returns a "true" value for BillingAgreementAcceptedStatus for my credentials, but I cannot see the BAID value in the response. Based on the testing with the the API Explorer I think I am missing one step, the one where I create the billing agreement. I can see that the Merchant API contains the SetExpressCheckout details, but I cannot find the CreateBillingAgreement.java. 

Am I missing something, or is create BAID not possible with this API? If it is could you please give me a clue on what to try next? Thank you!

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue. Merchant APIs are not actively developed, and all the new features are supported/delivered to REST APIs. Please use  https://github.com/paypal/PayPal-Java-SDK for any future developments.

**Comment by bdsl-foundry** [comment]
@sempervirescent I believe you still need to execute DoExpressCheckoutPayment but you can set the pyament amount to zero if you want to defer taking the payment, whether it will be deferred by milliseconds, seconds, or months.
