### ISSUE TITLE
PatternSyntaxException at com.paypal.core.soap.MerchantAPICallPreHandler.processPayLoadForFormatting

### ISSUE THREAD

**Issue by NamrataBagerwal** [paypal/merchant-sdk-java#27]
Hi, I am using merchant-sdk-java from maven in my android gradle project for express checkout integration and I am getting the following error:

    08-10 15:42:30.233 26631-26731/com.spec.paypalpoc W/System.err﹕ java.util.regex.PatternSyntaxException: Syntax error in regexp pattern near index 15:
    08-10 15:42:30.234 26631-26731/com.spec.paypalpoc W/System.err﹕ (?<!{[01]{1})}
    08-10 15:42:30.234 26631-26731/com.spec.paypalpoc W/System.err﹕ ^
    08-10 15:42:30.234 26631-26731/com.spec.paypalpoc W/System.err﹕ at java.util.regex.Pattern.compileImpl(Native Method)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at java.util.regex.Pattern.compile(Pattern.java:411)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at java.util.regex.Pattern.(Pattern.java:394)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at java.util.regex.Pattern.compile(Pattern.java:381)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at java.lang.String.replaceAll(String.java:1600)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at com.paypal.core.soap.MerchantAPICallPreHandler.processPayLoadForFormatting(MerchantAPICallPreHandler.java:466)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at com.paypal.core.soap.MerchantAPICallPreHandler.getPayLoadUsingSOAPHeader(MerchantAPICallPreHandler.java:447)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at com.paypal.core.soap.MerchantAPICallPreHandler.getPayLoad(MerchantAPICallPreHandler.java:317)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at com.paypal.core.BaseService.call(BaseService.java:264)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.setExpressCheckout(PayPalAPIInterfaceServiceService.java:2196)
    08-10 15:42:30.237 26631-26731/com.spec.paypalpoc W/System.err﹕ at urn.ebay.api.PayPalAPI.PayPalAPIInterfaceServiceService.setExpressCheckout(PayPalAPIInterfaceServiceService.java:2148)

So basically when I looked into this method: 

    /**
    	 * Process the payload before using message formatting
     */
    private String processPayLoadForFormatting(String payLoad) {
    	Matcher match = REGEX_PATTERN.matcher(payLoad);
    	StringBuffer sb = new StringBuffer();
    	while (match.find()) {
    		match.appendReplacement(sb, "'" + match.group());
    	}
    	match.appendTail(sb);
    	
    	// Fix json strings in element values by replacing {
    	// by '{' and matching } by '}'
    	return sb.toString().replaceAll("(?<!\\{[01]{1})}", "'}' ")
    			.replaceAll("\\{(?![01]})", "'{' ");
    }

We need to escape "}" in this line :   return sb.toString().replaceAll("(?<!\\{[01]{1})}", "'}' ")
				.replaceAll("\\{(?![01]})", "'{' ");

Kindly let me know about the action in the matter.
Thanks and Regards,
Namrata Bagerwal.

**Comment by juwlee** [comment]
Hi @NamrataBagerwal can you please share your request with confidential fields redacted?

**Comment by NamrataBagerwal** [comment]
Hi @juwlee I am using the following code snippet:

    PaymentDetailsType paymentDetails = new PaymentDetailsType();
    paymentDetails.setPaymentAction(PaymentActionCodeType.fromValue("Sale"));
    PaymentDetailsItemType item = new PaymentDetailsItemType();
    BasicAmountType amt = new BasicAmountType();
    amt.setCurrencyID(CurrencyCodeType.fromValue("USD"));
    double itemAmount = 1.00;
    amt.setValue(itemAmount);
    int itemQuantity = 1;
    item.setQuantity(itemQuantity);
    item.setName("item");
    item.setAmount(amt);
    	
    
    List<PaymentDetailsItemType> lineItems = new ArrayList<PaymentDetailsItemType>();
    lineItems.add(item);
    paymentDetails.setPaymentDetailsItem(lineItems);
    BasicAmountType orderTotal = new BasicAmountType();
    orderTotal.setCurrencyID(CurrencyCodeType.fromValue("USD"));
    orderTotal.setValue(itemAmount * itemQuantity); 
    paymentDetails.setOrderTotal(orderTotal);
    List<PaymentDetailsType> paymentDetailsList = new ArrayList<PaymentDetailsType>();
    paymentDetailsList.add(paymentDetails);
    
    SetExpressCheckoutRequestDetailsType setExpressCheckoutRequestDetails = new SetExpressCheckoutRequestDetailsType();
    setExpressCheckoutRequestDetails.setReturnURL("https://devtools-paypal.com/guide/expresscheckout?success=true");
    setExpressCheckoutRequestDetails.setCancelURL("https://devtools-paypal.com/guide/expresscheckout?cancel=true");
    
    setExpressCheckoutRequestDetails.setPaymentDetails(paymentDetailsList);
    
    SetExpressCheckoutRequestType setExpressCheckoutRequest = new SetExpressCheckoutRequestType(setExpressCheckoutRequestDetails);
    setExpressCheckoutRequest.setVersion("104.0");
    
    SetExpressCheckoutReq setExpressCheckoutReq = new SetExpressCheckoutReq();
    setExpressCheckoutReq.setSetExpressCheckoutRequest(setExpressCheckoutRequest);
    
    Map<String, String> sdkConfig = new HashMap<String, String>();
    sdkConfig.put("mode", "sandbox");
    sdkConfig.put("acct1.UserName", "jb-us-seller_api1.paypal.com");
    sdkConfig.put("acct1.Password", "WX4WTU3S8MY44S7F");
    sdkConfig.put("acct1.Signature","AFcWxV21C7fd0v3bYYYRCpSSRl31A7yDhhsPUU2XhtMoZXsWHFxu-RWy");
    PayPalAPIInterfaceServiceService service = new PayPalAPIInterfaceServiceService(sdkConfig);
    SetExpressCheckoutResponseType setExpressCheckoutResponse = service.setExpressCheckout(setExpressCheckoutReq);

from this link: https://devtools-paypal.com/guide/expresscheckout?interactive=ON&env=sandbox
And error is thrown on this line:
 SetExpressCheckoutResponseType setExpressCheckoutResponse = service.setExpressCheckout(setExpressCheckoutReq);

**Comment by juwlee** [comment]
@NamrataBagerwal Are you running the sample code on the devtools website? I can't seem to reproduce the error. Can you elaborate how to replicate it?

**Comment by NamrataBagerwal** [comment]
@juwlee This sample is running fine on devtools website but I am running it in Android Studio and the error described above is thrown internally.

**Comment by juwlee** [comment]
@NamrataBagerwal Please note that this SDK is designed to run on servers, not on mobile devices. PayPal MTS might be able to provide some information on mobile integration.

**Comment by biswajit123** [comment]
Hi @juwlee I have same issue like @NamrataBagerwal . Can you please share some suggestions how could we make a recurring payment in android with a trial period.

**Comment by juwlee** [comment]
@NamrataBagerwal as mentioned above, this SDK is designed to run on server-side environment. For mobile integration, please see [Braintree's V.Zero](https://www.braintreepayments.com/v.zero) or reach out to [Paypal MTS](https://www.paypal-techsupport.com/app/ask/session)
