### ISSUE TITLE
Slow enum.fromValue(String) performance

### ISSUE THREAD

**Issue by lesliel** [paypal/merchant-sdk-java#29]
The `fromValue(String)` functions in your `enums` (executed also on response parsing) are very slow and resource hungry: it compares strings one after the other, instead of using a **map of values**. Just imagine its performance for `CurrencyCodeType` or `CountryCodeType`...

(You should also consider to **externalize** the common (e.g. the new map building) logic -- I've seen far too many code duplication in the library...)

**Comment by pp-randy** [comment]
I apologize this SDK is not actively supported; however, pull requests would still be reviewed and considered. 

Have you already looked into https://github.com/paypal/PayPal-Java-SDK to see if it would meet your integration needs?

**Comment by lesliel** [comment]
Based on the [documentation](https://developer.paypal.com/docs/integration/direct/rest-api-payment-country-currency-support/):
> _the merchant must have a **Pro UK merchant account** with PayPal to process PayPal REST API direct credit card payments. This is the **only** supported merchant account for REST API **direct credit card payments** at this time._

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
