### ISSUE TITLE
Dependency resolution

### ISSUE THREAD

**Issue by osvadimos** [paypal/merchant-sdk-java#30]
In read me
`mvn install:install-file -Dfile=commons-codec-1.3.jar -DgroupId=commons-codec -DartifactId=commons-codec -Dversion=1.3 -Dpackaging=jar
mvn install:install-file -Dfile=paypal-core-1.0.jar -DgroupId=com.paypal.sdk -DartifactId=paypal-core -Dversion=1.0 -Dpackaging=jar
mvn install:install-file -Dfile=merchantsdk-2.11.117.jar -DgroupId=com.paypal.sdk -DartifactId=merchantsdk -Dversion=2.11.117 -Dpackaging=jar   `

![image](https://cloud.githubusercontent.com/assets/3665387/14766765/9820fcee-0a1e-11e6-935c-d40f28d72d54.png)

I'm getting this one

![image](https://cloud.githubusercontent.com/assets/3665387/14766774/c10f1ffa-0a1e-11e6-865e-27e64a72a5e7.png)

However here there is not 1.0
http://mvnrepository.com/artifact/com.paypal.sdk/paypal-core

So, should it not be adjusted to use one of the available?

To me 1.1 works fine though.

**Comment by pp-randy** [comment]
I think you should try to use the most recent versions of the merchant sdk and the paypal core; this is to prevent TLS issues, more here: https://github.com/paypal/tls-update

merchant (merchant 2.x)	2.14.117
sdk-core	1.7.0

**Comment by osvadimos** [comment]
Hi. 
 
Brilliant mate, thx a lot.

For some reason could not find this git repo myself.

Best regards.

Vadim.

**Comment by pp-randy** [comment]
I submitted a pull request for to update the readme, thank you @osvadimos 
https://github.com/paypal/merchant-sdk-java/pull/31
