### ISSUE TITLE
SDK_VERSION version in PayPalAPIInterfaceServiceService is incorrect

### ISSUE THREAD

**Issue by adinath-raveendraraj** [paypal/merchant-sdk-java#32]
The SDK_VERSION variable in class PayPalAPIInterfaceServiceService is set to "2.11.117", shouldn't this value be set to "2.14.117" instead? Does it matter?

**Comment by jaypatel512** [comment]
No, version numbers as long as they follow semver strategy are fine.

**Comment by adinath-raveendraraj** [comment]
I don't recall exactly what the context of this issue was, I believe the purpose of the issue was to point out that the value in PayPalAPIInterfaceServiceService.SDK_VERSION did not match the release version. Anyways, we ended up having to write our own client since this SDK was at version 124, where as the current API version is 204 -- so this issue is a little moot now :)
