### ISSUE TITLE
Mandatory SSL on returnUrl Express Checkout

### ISSUE THREAD

**Issue by lucabaggi** [paypal/merchant-sdk-java#36]
Hi,
is it possible that, due to some policy change, paypal sandbox do not accept returnUrl without SSL anymore? I noticed that if I pass returnUrl as http://localhost I got a redirect to cancelUrl, while passing https://localhost I got the expected redirect. 
The flow is:
- call setExpressCheckout with all params, and receive the token
- redirect to sandbox using the token
- login with sandbox account and confirm the payment
- if returnUrl is in https, sandbox redirect to returnUrl, else to cancelUrl

In every case, from sendbox user console I can see that the payment was accepted.

Thank you in advance

Luca

**Comment by jaypatel512** [comment]
Hey @lucabaggi !

I don't think so. We have not made any recent changes to this. Can you please make send us the return url that you get back in `http` and `https`. We were not able to reproduce this issue on our end. 

Thank you.

**Comment by lucabaggi** [comment]
Hi @jaypatel512 
I tried with localhost on port 9000 (because I'm working with Play framework), but also with our test environment I have the same behaviour (which I have not in production, where we have https). In particular, I use [http://localhost:9000/paypal/complete] as resultUrl, and [http://localhost:9000/paypal/cancel]. 
Also, trying with curl from command line (as explained in the documentation here [https://developer.paypal.com/docs/classic/express-checkout/gs_expresscheckout/#tryit]), I have the same issue, don't know why.

**Comment by dili91** [comment]
same problem here. if I choose an http returnUrl, i'm redirected to the cancelUrl even if the transaction was successfully completed. I think it's something related to a lower level than the Java SDK. In fact I get the same issue even when making raw HTTP requests

**Comment by ppmtscory** [comment]
@dili91 can you please provide your payment request so that we can try to reproduce?  We're not seeing any issues on our end with our tests.

**Comment by jaypatel512** [comment]
Closing this issue based on inactivity. Please re-open if you are still facing this issue.
