### ISSUE TITLE
Wrong currency reported in PaymentInfoType.getSettleAmount().getCurrencyID()

### ISSUE THREAD

**Issue by data-digger** [paypal/merchant-sdk-java#4]
This bug only affects accounts that accept multiple currencies and are set to convert incoming payments to primary currency.

When such payment is made (for example $5 USD, note that USD balance must not be opened for currency conversion to occur)  and primary account is set to PLN PaymentInfoType.getSettleAmount().getValue() returns correct value (i.e. at current exchange rate ~3PLN/USD it is ~15PLN). However PaymentInfoType.getSettleAmount().getCurrencyID() returns 'USD' instead of 'PLN'.

**Comment by juwlee** [comment]
@data-digger do you still see this issue? If so, could you share the full request/response SOAP envelopes with confidential information redacted?
