### ISSUE TITLE
Payment verification message is INVALID

### ISSUE THREAD

**Issue by piotrazz87** [paypal/merchant-sdk-java#40]
From yesterday I have problem with verification of pay pal payment on SANDBOX. Everything was working well till yesterday.  Below request of payment:

> https://www.sandbox.paypal.com/cgi-bin/webscr?cmd=_xclick&business=**************&no_shipping=1&currency_code=EUR&item_name=**************&amount=11.57&rm=2&return=**************&custom=**************&cancel_return=*************

and payload to paypall :

> cmd=_notify-validate&orderState=null&custom=****_&txn_id=**_&mc_currency=EUR&mc_fee=**\* &mc_gross=**_&protection_eligibility=ELIGIBLE&payment_date=**_&payment_fee=8**&payment_gross=**_&payment_status=Completed&payment_type=INSTANT_TRANSFER&business=_**&receiver_id=****&payer_email=****&payer_id=**_&payer_status=VERIFIED&first_name=Test&last_name=Buyer&item_name=_***&quantity=1&charset=UTF-8

Below is a fragment of code for transaction verification:

```
 final HttpConnection connection = ConnectionManager.getInstance().getConnection();
        try {
            connection.createAndconfigureHttpConnection(httpConfiguration);
            headerMap.put("Host", new URL("https://www.sandbox.paypal.com/cgi-bin/webscr").getHost());
             final String  paymentResponseResult = connection.execute(null, payload.toString(), headerMap);    // payload is above
        } catch (Exception e) {
            LoggingManager.debug(CustomIPNMessage.class, e.getMessage());
        }
```

versions:
compile group: 'com.paypal.sdk', name: 'merchantsdk', version:"2.5.106"

can you help me?

**Comment by pp-randy** [comment]
@piotrazz87 are you getting back unverified from PayPal or are you having an issue when making the connection?

If you are having a connection issue these might be helpful:
Update the postback URL to https://ipnpb.sandbox.paypal.com/cgi-bin/webscr
Review https://github.com/paypal/tls-update#java

**Comment by pp-randy** [comment]
Closing the issue.  Please let me know if you need further assistance.
