### ISSUE TITLE
I createRecurringPaymentsProfile and set initialAmount but can't receive IPN message

### ISSUE THREAD

**Issue by wjlight** [paypal/merchant-sdk-java#42]
hi~ my step is:  setExpressCheckout and set notifyURL  and get token, then set initialAmount and createRecurringPaymentsProfile,   but I can't receive the IPN message, something wrong with me?

**Comment by pp-randy** [comment]
Does the IPN Simulator work for you?  Please note you will need to log into the site to use it https://developer.paypal.com/developer/ipnSimulator/

**Comment by pp-randy** [comment]
Hi closing this issue, please let me know if you are needing further assistance.
